name: grpc_server
version: 1.0.0
description: A new Get Server application.
environment: 
  sdk: '>=2.12.0 <3.0.0'

dependencies: 
  get_server: 1.1.1
  grpc: ^3.0.2
  protobuf: ^2.1.0

dev_dependencies: 
  pedantic: 1.11.1
  test: 1.21.1

